[dms-plugins]
src.git = "https://github.com/AvengeMedia/dms-plugins"
fetch.github = "AvengeMedia/dms-plugins"

[helium]
src.github_tag = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64.AppImage"
